[program:xray]
command=/usr/local/bin/xray run -c /app/hamzaban/.xray/config.json
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
redirect_stderr=true
stdout_logfile=/app/hamzaban/.xray/xray.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3

[program:hamzaban]
command=/usr/local/bin/python3 /app/hamzaban/bot.py
directory=/app/hamzaban
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
redirect_stderr=true
stdout_logfile=/app/hamzaban/bot.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
