"""Formatting facade (REF2-T2).

Thin re-export shim over the split leaves — ``formatting_escape.py`` (T1),
``formatting_jalali.py`` + ``formatting_cards.py`` (T2). Every existing
``from services.utils.formatting import ...`` caller works unchanged; the
canonical definitions live in the leaves (old defs removed same PR).

Deliberately NOT re-exported: ``jdatetime`` (owned by the jalali leaf —
patch ``services.utils.formatting_jalali.jdatetime`` for the fallback path),
``APP_TZ``/``_app_today`` (owned by ``config`` — the display baseline is
``services.utils.formatting_jalali._app_today``).
"""

import random  # noqa: F401 — compat: origin surface exposed formatting.random
# (tests patch fmt.random.randrange); the canonical import lives in
# formatting_cards.py. Same stdlib singleton, no duplication, no cycle.

from services.utils.formatting_cards import (
    ASK_WORD_PROMPT,
    NEW_CARD_BADGE,
    SRS_FRONT_SUB_INSTRUCTION,
    SRS_HIDDEN_HEADER,
    SRS_HINT_ANTONYM,
    SRS_HINT_MEANING,
    SRS_HINT_SYNONYM,
    SRS_INSTRUCT_FILL_BLANK,
    SRS_INSTRUCT_STANDARD,
    SRS_POST_REVEAL,
    SRS_PROMPT_TYPES,
    CardPreparationError,
    _heat_label,
    _phonetic_code_spans,
    _saved_word_card,
    _stage_counts,
    _stage_for_record,
    _stage_modifier,
    _STAGE_ICON,
    _TIER_LABEL,
    _blank_word,
    _draw_synonym_items,
    _example_has_word,
    _fill_blank_hints,
    _hint_line,
    _join_guillemets,
    _synonym_instruct,
    days_since_review,
    eligible_srs_prompt_types,
    format_card,
    format_card_message,
    format_grammar_tip,
    format_next_review_text,
    format_review_badge,
    format_session_detail_page,
    format_session_summary,
    format_srs_back_stage,
    format_srs_front_stage,
    format_summary_legend,
    phonetic_lines,
    select_srs_prompt_type,
)
from services.utils.formatting_escape import (
    escape_mdv2,
    escape_mdv2_code,
    html_escape,
    to_persian_digits,
)
from services.utils.formatting_jalali import (
    _ISO_DAY_RE,
    _JALALI_MONTHS,
    _JALALI_WEEKDAYS,
    _app_date,
    _jalali_day_month,
    _parse_iso_to_app_tz,
    _relative_next_review,
    _to_jalali_str,
    _weekday_name,
    is_iso_day_key,
    jalali_day_label,
    jalali_time_label,
    parse_iso_to_app_tz,
    reports_day_sort_key,
    reports_jalali_group_key,
    to_jalali_str,
)

__all__ = [
    "ASK_WORD_PROMPT",
    "NEW_CARD_BADGE",
    "SRS_FRONT_SUB_INSTRUCTION",
    "SRS_HIDDEN_HEADER",
    "SRS_HINT_ANTONYM",
    "SRS_HINT_MEANING",
    "SRS_HINT_SYNONYM",
    "SRS_INSTRUCT_FILL_BLANK",
    "SRS_INSTRUCT_STANDARD",
    "SRS_POST_REVEAL",
    "SRS_PROMPT_TYPES",
    "CardPreparationError",
    "_heat_label",
    "_phonetic_code_spans",
    "_saved_word_card",
    "_stage_counts",
    "_stage_for_record",
    "_stage_modifier",
    "_STAGE_ICON",
    "_TIER_LABEL",
    "_blank_word",
    "_draw_synonym_items",
    "_example_has_word",
    "_fill_blank_hints",
    "_hint_line",
    "_join_guillemets",
    "_synonym_instruct",
    "days_since_review",
    "eligible_srs_prompt_types",
    "escape_mdv2",
    "escape_mdv2_code",
    "format_card",
    "format_card_message",
    "format_grammar_tip",
    "format_next_review_text",
    "format_review_badge",
    "format_session_detail_page",
    "format_session_summary",
    "format_srs_back_stage",
    "format_srs_front_stage",
    "format_summary_legend",
    "html_escape",
    "phonetic_lines",
    "select_srs_prompt_type",
    "to_persian_digits",
    "_ISO_DAY_RE",
    "_JALALI_MONTHS",
    "_JALALI_WEEKDAYS",
    "_app_date",
    "_jalali_day_month",
    "_parse_iso_to_app_tz",
    "_relative_next_review",
    "_to_jalali_str",
    "_weekday_name",
    "is_iso_day_key",
    "jalali_day_label",
    "jalali_time_label",
    "parse_iso_to_app_tz",
    "reports_day_sort_key",
    "reports_jalali_group_key",
    "to_jalali_str",
]
