"""Admin AI domain module (Finding #7 seam).

Expand step: this module re-exports the standalone AI/preset/fallback/custom-test
symbols currently living in the admin monolith so that task 7.5 (Batch A) can
move the ``admin:ai_preset*``/``admin:ai_fallback*``/``admin:ai_custom_test*``
handler logic here without changing call sites. Behavior is unchanged; nothing
routes to this module yet. AI functions are re-exported from ``handlers.admin``
and AI keyboards from ``config.keyboards`` (verbatim).
"""

from handlers.admin import (
    _activate_ai_preset,
    _add_ai_preset,
    _confirm_save_preset,
    _custom_test_step_goal,
    _custom_test_step_lang,
    _custom_test_step_level,
    _custom_test_step_preset,
    _custom_test_step_target,
    _delete_ai_preset,
    _detect_key_groups,
    _discard_all_preset_changes,
    _edit_ai_preset,
    _edit_ai_preset_field,
    _handle_ai_fallback,
    _handle_ai_preset_field_input,
    _handle_ai_preset_new_name,
    _handle_custom_test_wizard,
    _handle_fallback_rank,
    _handle_full_edit_cancel,
    _handle_full_edit_input,
    _handle_full_edit_next,
    _handle_full_edit_pick_group,
    _handle_full_edit_save,
    _handle_full_edit_skip,
    _handle_group_batch_key,
    _handle_group_manager_clear,
    _handle_group_manager_rename,
    _handle_group_set_label,
    _handle_group_view,
    _key_hash,
    _run_custom_test,
    _save_ai_preset,
    _show_ai_fallback,
    _show_ai_preset_view,
    _show_ai_presets,
    _show_ai_settings,
    _show_fallback_chain,
    _show_fallback_preset_picker,
    _show_fallback_usage_details,
    _show_group_manager,
    _show_grouped_presets,
    _show_help_fallback_chain,
    _show_help_presets,
    _show_linear_presets,
    _show_wizard_field,
    _show_wizard_summary,
    _start_custom_test_wizard,
    _start_full_edit_wizard,
    _test_ai_connection,
    _toggle_preset_view_mode,
    _validate_wizard_value,
)
from config.keyboards import (
    ai_fallback_keyboard,
    ai_preset_edit_keyboard,
    ai_preset_view_keyboard,
    ai_presets_list_keyboard,
    ai_settings_keyboard,
    fallback_chain_keyboard,
)

__all__ = [
    "_activate_ai_preset",
    "_add_ai_preset",
    "_confirm_save_preset",
    "_custom_test_step_goal",
    "_custom_test_step_lang",
    "_custom_test_step_level",
    "_custom_test_step_preset",
    "_custom_test_step_target",
    "_delete_ai_preset",
    "_detect_key_groups",
    "_discard_all_preset_changes",
    "_edit_ai_preset",
    "_edit_ai_preset_field",
    "_handle_ai_fallback",
    "_handle_ai_preset_field_input",
    "_handle_ai_preset_new_name",
    "_handle_custom_test_wizard",
    "_handle_fallback_rank",
    "_handle_full_edit_cancel",
    "_handle_full_edit_input",
    "_handle_full_edit_next",
    "_handle_full_edit_pick_group",
    "_handle_full_edit_save",
    "_handle_full_edit_skip",
    "_handle_group_batch_key",
    "_handle_group_manager_clear",
    "_handle_group_manager_rename",
    "_handle_group_set_label",
    "_handle_group_view",
    "_key_hash",
    "_run_custom_test",
    "_save_ai_preset",
    "_show_ai_fallback",
    "_show_ai_preset_view",
    "_show_ai_presets",
    "_show_ai_settings",
    "_show_fallback_chain",
    "_show_fallback_preset_picker",
    "_show_fallback_usage_details",
    "_show_group_manager",
    "_show_grouped_presets",
    "_show_help_fallback_chain",
    "_show_help_presets",
    "_show_linear_presets",
    "_show_wizard_field",
    "_show_wizard_summary",
    "_start_custom_test_wizard",
    "_start_full_edit_wizard",
    "_test_ai_connection",
    "_toggle_preset_view_mode",
    "_validate_wizard_value",
    "ai_fallback_keyboard",
    "ai_preset_edit_keyboard",
    "ai_preset_view_keyboard",
    "ai_presets_list_keyboard",
    "ai_settings_keyboard",
    "fallback_chain_keyboard",
]
